### ISSUE TITLE
Upgrade to v5.1.5

### ISSUE THREAD

**Issue by fbruetting** [flathub/org.kicad_pcb.KiCad#23]
Would be neat!

**Comment by jmaibaum** [comment]
A pull request exists in #22.

**Comment by jmaibaum** [comment]
And a second one exists in #24 (which also switches source download to Gitlab, where the project has been moved).

**Comment by jmaibaum** [comment]
@bilelmoussaoui Thanks for merging #24! Something seems to have been going wrong during the build though, see https://flathub.org/builds/#/builders/32/builds/15487

According to https://flathub.org/builds/#/builders/19/builds/1818, the "Generate deltas" step timed out after 20:00 mins. Since this has never happened during the test builds during the PR phase, I have no idea what went wrong. Do you have any idea what has happened?

**Comment by bilelmoussaoui** [comment]
I triggered a new build, let's see if we can reproduce that.

**Comment by jmaibaum** [comment]
Looks as if all is OK now, see https://flathub.org/builds/#/builders/32/builds/15522

Thanks @bilelmoussaoui!

**Comment by bilelmoussaoui** [comment]
Perfext, we can close this issue then.
